# action.yml
name: 'Create PDF'
description: 'Creates PDF files from github markdown'
runs:
  using: 'docker'
#   image: 'docker://docker.pkg.github.com/mrtj/actions-makepdfs/makepdfs:latest'
  image: 'docker://janostolgyesi/actions-makepdfs:latest'

inputs:
  markdown_dir:
    description: 'Location of markdown files in github repository'
    required: true
    default: 'doc'
  output_dir:
    description: 'Location to output PDF files to'
    required: true
    default: 'tmp'
  assets_dir:
    description: 'Location of template/template.html and styles/markdown[-pdf].css'
    required: true
    default: 'doc_assets'  

branding:
  icon: 'activity'
  color: 'green'
